task: {
  grid-rows: 2
  grid-columns: 1
  horizontal-gap: 0
  vertical-gap: 6
  label: "👤⚙✉📃A-oo1"
  style: {
    font-size: 18
  }
  desc: {
    shape: text
    label: "注文を検索するああああ\nその後何々する"
  }

  icon-bottom: {
    shape: image
    label: ""
    icon: https://icons.d2lang.com/aws%2FDeveloper%20Tools%2FAWS-CodeDeploy.svg
    style: {
      stroke-width: 0
      fill: transparent
    }
    width: 24
    height: 24
  }
}
